deploy:
  stage: deploy
  script:
    - mkdir ~/.ssh
    - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh -o "StrictHostKeyChecking=no" $SERVER 'cd ~/git-ch && git pull origin master && pm2 restart git-ch'
