deploy:
  stage: deploy
  only:
    - master
  script:
    - mkdir ~/.ssh
    - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh -o "StrictHostKeyChecking=no" $SERVER 'bash deploy_setup.sh'
